apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcsfuse-debugger-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: gcsfuse-debugger
