apiVersion: batch/v1
kind: Job
metadata:
  name: samplejob-$(JOB_INDEX)
  namespace: default
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  backoffLimit: 1
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: default
      containers:
        - name: prewarm-inodes
          image: busybox
          command: ["/bin/sh", "-c"]
          env:
            - name: JOB_INDEX
              value: "1"
          args:
            - |
              echo "[INFO] Prewarming inodes via stat for job $(JOB_INDEX)..."
              cd /content        
              echo "hello" > target-$(JOB_INDEX).txt
              ln -s target-$(JOB_INDEX).txt link-$(JOB_INDEX).txt
              mv link-$(JOB_INDEX).txt renamed-$(JOB_INDEX).txt
          volumeMounts:
            - name: gcs
              mountPath: /content
      volumes:
        - name: gcs
          persistentVolumeClaim:
            claimName: gcsfuse-debugger-pvc
      restartPolicy: Never